project:
  type: website

website:
  title: "Brian Vancil's blog"
  site-url: https://bvancil.github.io/blog/
  description: "A blog about data science, programming, and reflection"
  open-graph:
    locale: en_US
  cookie-consent:
    type: express
  comments:
    utterances: 
      repo: bvancil/blog
      theme: github-dark
      label: comment
      issue-term: pathname
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: mastodon
        href: https://fosstodon.org/@bvancil
      - icon: linkedin
        href: https://www.linkedin.com/in/brianvancil/
      - icon: github
        href: https://github.com/bvancil
  page-footer:
    center:
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license-blog.qmd
format:
  html:
    theme:
      light: zephyr
      dark: cyborg
    css: style/style.scss
execute: 
  freeze: auto
