---
title: "Probabilistic workflow using Stan"
author: "Brian Vancil"
date: "2024-06-30"
categories: [data_science, Stan, workflow]
kernel: julia
---

To illustrate workflow with Stan and Julia, let's consider a situation in which salaries are based, imperfectly, on a number of latent talents. Additionally, let us assume that there are some underlying biases on the basis of protected characteristics, like sex and race/ethnicity. Let us see how sensitive our regression methods are to discovering these biases.

We load a number of Julia packages to process tabular data, work with random distributions, etc.

```{julia}
# packages
using CategoricalArrays
using DataFrames
using DataFramesMeta
using Distributions
using GLM
# using Lathe
# using MLBase
# using Plots
using StableRNGs
using StatsModels
# using StatsPlots

# built-in packages
using Random
```

## Generating synthetic data

### Generating parameters

We use $N$ for the number of individuals with salaries and $G$ for the number of groups (think: departments or job classes).

```{julia}
N = 1000
G = 20
```

We generate the sizes of each department by using a categorical distribution where the probabilities are normalized from draws from the uniform distribution. For each $g = 1, \ldots, G$,

$$
\begin{aligned}
P_g &\sim \text{Uniform}(0, 1) \\
p_g &= \frac{P_g}{\sum\limits_h P_h}.
\end{aligned}
$$

```{julia}
Random.seed!(20240721)

P_group = rand(Uniform(), G)
p_group = P_group ./ sum(P_group)
```

Without loss of generality, we sort these by renumbering the groups.

```{julia}
p_group = reverse(sort(p_group))
```

It's time to start considering the group parameters as a data frame.

```{julia}
group_params = DataFrame(id_group = 1:G, p_group = p_group)
```

We can add more parameters as necessary. Since we imagine salary to be log-normally distributed, with a distribution that may differ by group, we set mu and sigma, through the CV (coefficient of variation), for each group.

```{julia}
transform!(group_params, [] => (() -> rand(Uniform(10.3, 12.8), G)) => :μ)
transform!(group_params, [] => (() -> rand(Uniform(0.03, 0.15), G)) => :cv)
transform!(group_params, [:μ, :cv] => ((μ, cv) -> μ .* cv) => :σ)
```

We can also calculate the exponentiated mean, median, mode, standard deviation, etc.

```{julia}
transform!(group_params, [:μ] => ((μ) -> exp.(μ)) => :median)
transform!(group_params, [:μ, :σ] => ((μ, σ) -> exp.(μ .- σ.^2)) => :mode)
transform!(group_params, [:μ, :σ] => ((μ, σ) -> exp.(μ .+ 0.5.*σ.^2)) => :mean)
transform!(group_params, [:mean, :σ] => ((mean, σ) -> mean .* sqrt.(exp.(σ.^2) .- 1)) => :std_dev)
transform!(group_params, [:σ] => ((σ) -> (exp.(σ.^2) .+ 2) .* sqrt.(exp.(σ.^2) .- 1)) => :skewness)
transform!(group_params, [:σ] => ((σ) -> (exp.(4 .* σ.^2) .+ 2 .* exp.(3 .* σ.^2) .+ 3 .* exp.(2 .* σ.^2) .- 6)) => :excess_kurtosis)
```

We can then assign all $N$ individuals to groups, similarly renumbering them to order by group.

```{julia}
group = rand(Categorical(p_group), N)
group = sort(group)
```

We begin to assemble this into a data frame.

```{julia}
individual_parameters = DataFrame(id_group = group)
```

How many latent skills should we include? Let's call that number $S$.

```{julia}
S = 5
skill_names = [Symbol("skill_$i") for i in 1:S]
```

```{julia}
skills_data = rand(Normal(), (N, S))
```

```{julia}
insertcols!(individual_parameters, (skill_names .=> eachcol(skills_data))...)
```

### Cleaning up: Assembling private parameters into a function

Scripts are nice for testing things, but we should refactor our code into a function so that we can run many possible scenarios. Here's the basic architecture:

```{mermaid}
---
title: Data flow
---
flowchart LR
    n_skills --> universal_parameters
    n_groups --> group_parameters
    universal_parameters --> group_parameters
    group_parameters --> private_parameters
    n_people --> private_parameters
    private_parameters --> public_parameters
    n_observable_skills --> public_parameters
    skill_noise --> public_parameters
    salary_noise --> public_parameters
```

```{julia}
# Returns parameters governing all observation
function universal_parameters(rng, n_skills, p_protected, β_protected)
    universal_params = DataFrame(
        # Location parameters
        μ_lo = 10.3,
        μ_hi = 12.8,
        # Coefficient of variation
        cv_lo = 0.03,
        cv_hi = 0.15,
        # Number of latent skills
        n_skills = n_skills,
        # Protected characteristic
        p_protected = p_protected,
        β_protected = β_protected
    )
    β_names = [Symbol("β_skill_$i") for i in 1:n_skills]
    β = rand(rng, Normal(), (1, n_skills))
    insertcols!(universal_params, (β_names .=> eachcol(β))...)
end

# Returns group parameters for n_groups, sorted in reverse by frequency
function group_parameters(rng, n_groups, universal_params)
    relative_group_frequency = rand(rng, Uniform(), n_groups)
    # Normalize to get probabilities
    group_probabilities = relative_group_frequency ./ sum(relative_group_frequency)
    group_probabilities = reverse(sort(group_probabilities))
    group_params = DataFrame(id_group = 1:n_groups, p_group = group_probabilities)
    group_params = crossjoin(group_params, universal_params)
    transform!(group_params, [:μ_lo, :μ_hi] => ((μ_lo, μ_hi) -> rand.(Uniform.(μ_lo, μ_hi), 1) |> Iterators.flatten |> collect) => :μ)
    transform!(group_params, [:cv_lo, :cv_hi] => ((cv_lo, cv_hi) -> rand.(Uniform.(cv_lo, cv_hi), 1) |> Iterators.flatten |> collect) => :cv)
    transform!(group_params, [:μ, :cv] => ((μ, cv) -> μ .* cv) => :σ)
    transform!(group_params, [:μ] => ((μ) -> exp.(μ)) => :median)
    transform!(group_params, [:μ, :σ] => ((μ, σ) -> exp.(μ .- σ.^2)) => :mode)
    transform!(group_params, [:μ, :σ] => ((μ, σ) -> exp.(μ .+ 0.5.*σ.^2)) => :mean)
    transform!(group_params, [:mean, :σ] => ((mean, σ) -> mean .* sqrt.(exp.(σ.^2) .- 1)) => :std_dev)
    transform!(group_params, [:σ] => ((σ) -> (exp.(σ.^2) .+ 2) .* sqrt.(exp.(σ.^2) .- 1)) => :skewness)
    transform!(group_params, [:σ] => ((σ) -> (exp.(4 .* σ.^2) .+ 2 .* exp.(3 .* σ.^2) .+ 3 .* exp.(2 .* σ.^2) .- 6)) => :excess_kurtosis)
    group_params
end

# Generates groups from parameters and number of people
function groups(rng, group_params, n_people)
    group = rand(rng, Categorical(group_params[!, :p_group]), n_people)
    group = sort(group)
    DataFrame(id_group = categorical(group))
end

function protected(rng, group_params, n_people)
    p_protected = minimum(group_params[:, :p_protected])
    protected_group = rand(rng, Categorical([1 - p_protected, p_protected]), n_people) .- 1
    protected_group = protected_group .- mean(protected_group)
    DataFrame(cind_protected = protected_group)
end

function skills(rng, n_skills, n_people)
    skill_names = [Symbol("skill_$i") for i in 1:n_skills]
    skill_data = rand(rng, Normal(), (n_people, n_skills))
    DataFrame(skill_data, skill_names)
end

function private_parameters(rng, n_people, group_params)
    n_skills = minimum(group_params[:, :n_skills])
    private_params = groups(rng, group_params, n_people)
    DataFrames.hcat!(private_params, protected(rng, group_params, n_people))
    if 0 < n_skills
        DataFrames.hcat!(private_params, skills(rng, n_skills, n_people))
    end
    private_params = innerjoin(private_params, group_params, on=:id_group)
    
    μ = private_params[:, :μ]
    cind_protected = private_params[:, :cind_protected]
    β_protected = minimum(private_params[:, :β_protected])
    expected_log_salary = μ + cind_protected * β_protected
    if 0 < n_skills
        β_skill = Matrix(select(private_params, Cols(x -> startswith(x, "β_skill_"))))'[:, 1]
        X_skill = Matrix(select(private_params, Cols(x -> startswith(x, "skill_"))))
        expected_log_salary += X_skill * β_skill
    end
    σ = private_params[:, :σ]
    log_salary = [rand(rng, Normal(μ1, σ1)) for (μ1 , σ1) in zip(expected_log_salary, σ)]

    insertcols!(private_params, :expected_log_salary => expected_log_salary, :val_log_salary => log_salary)
    private_params
end

function public_parameters(rng, private_params, n_observable_skills, skill_noise, salary_noise)
    n_people = nrow(private_params)
    observable_skill_names = [Symbol("skill_$i") for i in 1:n_observable_skills]
    public_params = select(private_params, :id_group, :cind_protected, observable_skill_names..., :val_log_salary)
    # add noise
    transform!(public_params, [:val_log_salary] => (s -> s .+ rand(rng, Normal(0, salary_noise), n_people)) => :val_log_salary)
    transform!(public_params, observable_skill_names .=> Ref(s -> s .+ rand(rng, Normal(0, skill_noise), n_people)) .=> observable_skill_names)
    public_params
end

rng = StableRNG(20240721)
S = 5
p_protected = 0.5
β_protected = -0.05
universal_params = universal_parameters(rng, S, p_protected, β_protected)
G = 10
group_params = group_parameters(rng, G, universal_params)
N = 1000
private_params = private_parameters(rng, N, group_params)
s = 3
public_params = public_parameters(rng, private_params, s, 0.1, 0)
```

Here, we have imagined $\forall i\in\lbrace 1\ldots N\rbrace$, where $g(i)$ is the group of the $i\text{th}$ person. 

$$
\log \text{Salary}_{i} \sim \text{Normal}(\mu_{g(i)} + \sum\limits_{j=1}^{S} \text{Skill}_{ij}\beta_j, \sigma^2_{g(i)})
$$

Only some of the skills ($s$ of $S$) are measured, and these with Gaussian noise `skill_noise`. Optionally, one can add in `salary_noise`, but we give the HR team the benefit of the doubt in assigning salary.

We added quite a few things in cleaning this up, which we hope are self-explanatory, like calculating the salary.

```{julia} 
# log_formula = @formula(val_log_salary ~ 1 + id_group + cind_protected + skill_1 + skill_2 + skill_3) 
log_formula = term(:val_log_salary) ~ sum(term.((1, :id_group, :cind_protected, [Symbol("skill_$i") for i in 1:s]...)))
log_model = lm(log_formula, public_params, contrasts = Dict(:id_group => EffectsCoding()))
```

Let's play with extracting information from this model to work towards building simulations to check the converage of $\beta_{\text{protected}}$.

```{julia}
cind_protected = findall(termnames(log_model)[2] .== "cind_protected")
β_protected_conf = confint(log_model)[cind_protected, :]
β_protected = universal_params[:, :β_protected][1]
@show(β_protected, β_protected_conf)
```

We'll now create a function that simulates many draws of data and tells us what fraction of times our confidence interval contains the true value. We might expect 95%, but the amount could be modified by the unmeasured variables, so let's check.

```{julia}
function simulate_models(rng, n_models, S, s, skill_noise)
    p_protected = 0.5
    β_protected = -0.05
    ind_coverage = Vector{Int64}(undef, n_models)
    for i in 1:n_models
        # Build data
        universal_params = universal_parameters(rng, S, p_protected, β_protected)
        G = 10
        group_params = group_parameters(rng, G, universal_params)
        N = 1000
        private_params = private_parameters(rng, N, group_params)
        public_params = public_parameters(rng, private_params, s, skill_noise, 0)
        # Build model
        log_formula = term(:val_log_salary) ~ sum(term.((1, :id_group, :cind_protected, [Symbol("skill_$i") for i in 1:s]...)))
        log_model = lm(log_formula, public_params, contrasts = Dict(:id_group => EffectsCoding()))
        # Extract from model
        cind_protected = findall(coefnames(log_model) .== "cind_protected")
        β_protected_conf = confint(log_model)[cind_protected, :]
        ind_coverage[i] = (β_protected_conf[1] <= β_protected <= β_protected_conf[2]) ? 1 : 0
    end
    mean(ind_coverage)
end

simulate_models(rng, 1000, 5, 3, 0.0)
```

This is excellent! Even in the presence of unmeasured information and group heteroscedasticity, our power to infer $\beta_{\text{protected}}$ is quite high, near the expected $1-\alpha=0.95$.

